name: Firebase deploy

on:
  push:
    branches: [ master ]

jobs:
  build & deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'
    - name: Install all packages
      run: yarn install
    - name: Build & export to static html/css/js
      run: yarn build
    - name: Install Firebase tools
      run: yarn global add firebase-tools
    - name: Deploy to Firebase Hosting
      run: firebase-tools deploy --token $FIREBASE_TOKEN
